<?php

namespace AppBundle\Repository\Product;

/**
 * CategoryAttributeValueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryAttributeValueRepository extends \Doctrine\ORM\EntityRepository
{
}
