<?php

namespace AppBundle\Repository\Product;

/**
 * ImageProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ImageProductRepository extends \Doctrine\ORM\EntityRepository
{
//      function FindByPage() {
//        $dql = $this->getEntityManager()
//                ->createQueryBuilder()
//                ->select('p')
//                ->from('AppBundle:Product\Product', 'p')
//                ->select('i')
//                ->from('AppBundle:Product\ImageProduct', 'i')
//                ->leftJoin('p', 'i.type')
//        ;
//
//        return $dql;
//    }
}
