<?php

namespace AppBundle\Repository\Product;

use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends EntityRepository {

    function cartFind($cart) {
//        var_dump($cart);


        foreach ($cart as $key => $c) {
//            echo $key . "=>" . $c . "<br>";

            $records[$key] = $this->getEntityManager()
                    ->createQueryBuilder()
                    ->select('p')
                    ->from('AppBundle:Product\Product', 'p')
                    ->where('p.id = :key')
                    ->setParameter('key', $key)
                    ->getQuery()
                    ->getSingleResult();
        }
        return $records;
    }

}
